builds:
  -
    ldflags:
      - -s -w -extldflags "-static" -X main.build={{.Version}}

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - freebsd
      - windows
      - darwin

    goarch:
      - amd64
      - arm64