builds:
  -
    ldflags:
      - -s -w -extldflags "-static" -X main.build={{.FullCommit}}

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - arm
      - 386
      - amd64
      - arm64